openapi: 3.0.0
info:
  version: 1.0.0
  title: dcwc
  description: dcws
servers:
  - url: 'https://us-central1-smartapi-295619.cloudfunctions.net/DigiCertApttusWS_CF/contract'
paths:
  '/id/{accountID}/product_id/{productId}':
    get:
      summary: Returns a user by ID
      parameters:
        - name: accountID
          in: path
          required: true
          description: The Account ID
          schema:
            type: string
        - name: productId
          in: path
          required: true
          description: 'The productId search string - 95, 97'
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  contract:
                    type: object
                    properties:
                      type:
                        type: string
                        minLength: 1
                      adjustment:
                        type: string
                      overall_discount_percent:
                        type: number
                      owner_email:
                        type: string
                        minLength: 1
                      total_size:
                        type: number
                      entitlements:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          required:
                            - product_id
                            - product_name
                            - term
                            - currency
                            - list_price
                            - discount_price
                            - discount_percent
                          properties:
                            product_id:
                              type: string
                              minLength: 1
                            product_name:
                              type: string
                              minLength: 1
                            term:
                              type: string
                              minLength: 1
                            currency:
                              type: string
                            list_price:
                              type: number
                            discount_price:
                              type: number
                            discount_percent:
                              type: number
                    required:
                      - type
                      - adjustment
                      - overall_discount_percent
                      - owner_email
                      - total_size
                      - entitlements
                  time_to_run:
                    type: string
                    minLength: 1
                  product_id_search:
                    type: string
                    minLength: 1
                required:
                  - contract
                  - time_to_run
                  - product_id_search
              examples:
                example-1:
                  value:
                    contract:
                      type: string
                      adjustment: string
                      overall_discount_percent: 0
                      owner_email: string
                      total_size: 0
                      entitlements:
                        - product_id: string
                          product_name: string
                          term: string
                          currency: string
                          list_price: 0
                          discount_price: 0
                          discount_percent: 0
                    time_to_run: string
                    product_id_search: string
        '400':
          description: The specified user ID is invalid (e.g. not a number)
        '404':
          description: A user with the specified ID was not found
      operationId: ''
      description: Desc
    parameters: []
  /id_search_names:
    get:
      summary: Get Id search strings
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - 'true'
                  properties: {}
      operationId: get-names
